package postory_server

var carrierTokensByName = map[string]string{
	"apc_postal":        "APC Postal",
	"australia_post":    "Australia Post",
	"aramex":            "Aramex",
	"asendia_us":        "Asendia",
	"axlehire":          "AxleHire",
	"borderguru":        "BorderGuru",
	"boxberry":          "Boxberry",
	"bring":             "Bring",
	"canada_post":       "Canada Post",
	"cdl":               "CDL",
	"correios_br":       "Correios Brazil",
	"correos_espana":    "Correos Espana",
	"collect_plus":      "Collect Plus",
	"couriersplease":    "Couriers Please",
	"deutsche_post":     "Deutsche Post",
	"dhl_benelux":       "DHL Benelux",
	"dhl_germany":       "DHL Germany",
	"dhl_ecommerce":     "DHL eCommerce",
	"dhl_express":       "DHL Express",
	"dpd_germany":       "DPD Germany",
	"dpd_uk":            "DPD UK",
	"estafeta":          "Estafeta",
	"fastway_australia": "Fastway Australia",
	"fedex":             "FedEx",
	"gls_de":            "GLS Germany",
	"gls_fr":            "GLS France",
	"globegistics":      "Globegistics",
	"gophr":             "Gophr",
	"gso":               "GSHO",
	"hermes_uk":         "Hermes UK",
	"hongkong_post":     "HongKong Post",
	"lasership":         "Lasership",
	"mondial_replay":    "Mondial Relay",
	"new_zealand_post":  "New Zealand Post",
	"newgistics":        "Newgistics",
	"nippon_express":    "Nippon Express",
	"ontrac":            "OnTrac",
	"orangeds":          "OrangeDS",
	"parcel":            "Parcel",
	"posti":             "Posti",
	"purolator":         "Purolator",
	"rr_donnelley":      "RR Donnelley",
	"russian_post":      "Russian Post",
	"sendle":            "Sendle",
	"skypostal":         "SkyPostal",
	"stuart":            "Stuart",
	"ups":               "UPS",
	"usps":              "USPS",
	"yodel":             "Yodel",
	"shippo":            "Shippo", // Shippo is used for test mode
}

func isCarrierSupported(carrierString string) bool {
	_, ok := carrierTokensByName[carrierString]
	return ok
}
