AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation stack for Postory

Parameters:
  Stage:
    Type: String
    Default: test

Mappings:
  Tokens:
    prod:
      Shippo: ''
    test:
      Shippo: ''

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 15
    Environment:
      Variables:
        SHIPPO_TOKEN: !FindInMap [ Tokens, !Ref Stage, Shippo ]
        STAGE: !Ref Stage

Resources:
  Track:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: track
      Handler: ./build/track
      Events:
        TrackApi:
          Type: Api
          Properties:
            Path: /track
            Method: GET
      Policies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: !GetAtt [Archive, Arn]

  History:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: history
      Handler: ./build/history
      Events:
        HistoryApi:
          Type: Api
          Properties:
            Path: /history
            Method: GET

  Archive:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: archive
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TrackInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: track-invocations-alarm
      AlarmDescription: Alarm for sum(invocations) of track API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref Track
      MetricName: Invocations
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 100
      Unit: Count
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      TreatMissingData: notBreaching

  TrackErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: track-errors-alarm
      AlarmDescription: Alarm for sum(errors) of track API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref Track
      MetricName: Errors
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 5
      Unit: Count
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      TreatMissingData: notBreaching

  TrackDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: track-duration-alarm
      AlarmDescription: Alarm for max(duration) of track API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref Track
      MetricName: Duration
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 10
      Unit: Seconds
      EvaluationPeriods: 1
      Period: 300
      Statistic: Maximum
      TreatMissingData: notBreaching

  HistoryInvocationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: history-invocations-alarm
      AlarmDescription: Alarm for sum(invocations) of history API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref History
      MetricName: Invocations
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 100
      Unit: Count
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      TreatMissingData: notBreaching

  HistoryErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: history-errors-alarm
      AlarmDescription: Alarm for sum(errors) of history API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref History
      MetricName: Errors
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 5
      Unit: Count
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      TreatMissingData: notBreaching

  HistoryDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: history-duration-alarm
      AlarmDescription: Alarm for max(duration) of history API
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref History
      MetricName: Duration
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 10
      Unit: Seconds
      EvaluationPeriods: 1
      Period: 300
      Statistic: Maximum
      TreatMissingData: notBreaching

  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: aws-spending-alarm
      AlarmDescription: Alarm for AWS spending
      AlarmActions:
        - !Ref EmailTopic
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
        - Name: Currency
          Value: USD
      Statistic: Maximum
      Period: 21600
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold

  EmailTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: email-topic
      Subscription:
        - Endpoint: andynguyenswe@gmail.com
          Protocol: email
