AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation stack for Postory

Parameters:
  ShippoToken:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: go1.x
    MemorySize: 128
    Timeout: 15
    Environment:
      Variables:
        SHIPPO_TOKEN: !Ref ShippoToken

Resources:
  Track:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: track
      Handler: ./build/track
      Events:
        TrackApi:
          Type: Api
          Properties:
            Path: /track
            Method: GET
      Policies:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: !GetAtt [Archive, Arn]

  History:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: history
      Handler: ./build/history
      Events:
        HistoryApi:
          Type: Api
          Properties:
            Path: /history
            Method: GET

  Archive:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: archive
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
